import { Inter } from "next/font/google";
import "./globals.css";
import '@mdxeditor/editor/style.css'
import Header from '../components/Header'
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
        <body className={inter.className + "bg:"}>
          <Header/>
            <Suspense>
              {children}
              {modal}
            </Suspense>
            <div id="modal-root" />
        </body>
    </html>
  );
}
